version: '2'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/ngnix/production/Dockerfile
    extends:
      file: docker-compose.yml
      service: server
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    depends_on:
      - server
  environment:
    RAILS_ENV: production
    DB_HOST: fargatetest.ap-northeast-1.rds.amazonaws.com
    DB_USERNAME: aresuke
    DB:PASSWORD: passwod
    DB:DATABASE: fargatetestdb